//Auto generated by Melexis TH71221 Register Calculator
//Fairbridge Technologies 2004
//J van Aardt


 // 19 July 2005

 #define MEL_REGA_LOADVAL_STANDBY  0x0029f050
 #define MEL_REGA_LOADVAL_TX_LVL0       0x00293850
 #define MEL_REGA_LOADVAL_TX_LVL1       0x00297850
 #define MEL_REGA_LOADVAL_TX_LVL2       0x0029b850
 #define MEL_REGA_LOADVAL_TX_LVL3       0x0029f850
 #define MEL_REGA_LOADVAL_RX       0x0029f450
 #define MEL_REGB_LOADVAL  0x00580050 
 #define MEL_REGC_LOADVAL_TX_433  0x00ac115e 
 #define MEL_REGC_LOADVAL_TX_403  0x00ac1137 
 #define MEL_REGC_LOADVAL_RX_433  0x00a0115e 
 #define MEL_REGC_LOADVAL_RX_403  0x00a01137 
 #define MEL_REGD_LOADVAL_403  0x00e810cc 
 #define MEL_REGD_LOADVAL_433  0x00e810f3 

